# Generated by Django 3.1.1 on 2021-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valauth',
            name='unic_token',
            field=models.CharField(default='42ac420e', max_length=8, null=True, unique=True),
        ),
    ]
