# Generated by Django 3.1.1 on 2021-04-01 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientListDevice',
            fields=[
                ('imei', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientlistdevice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameValueClientDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val0', models.CharField(blank=True, default='Val0', max_length=50, null=True)),
                ('val1', models.CharField(blank=True, default='Val1', max_length=50, null=True)),
                ('val2', models.CharField(blank=True, default='Val2', max_length=50, null=True)),
                ('val3', models.CharField(blank=True, default='Val3', max_length=50, null=True)),
                ('val4', models.CharField(blank=True, default='Val4', max_length=50, null=True)),
                ('val5', models.CharField(blank=True, default='Val5', max_length=50, null=True)),
                ('val6', models.CharField(blank=True, default='Val6', max_length=50, null=True)),
                ('val7', models.CharField(blank=True, default='Val7', max_length=50, null=True)),
                ('val8', models.CharField(blank=True, default='Val8', max_length=50, null=True)),
                ('val9', models.CharField(blank=True, default='Val9', max_length=50, null=True)),
                ('val10', models.CharField(blank=True, default='Val10', max_length=50, null=True)),
                ('val11', models.CharField(blank=True, default='Val11', max_length=50, null=True)),
                ('val12', models.CharField(blank=True, default='Val12', max_length=50, null=True)),
                ('val13', models.CharField(blank=True, default='Val13', max_length=50, null=True)),
                ('val14', models.CharField(blank=True, default='Val14', max_length=50, null=True)),
                ('val15', models.CharField(blank=True, default='Val15', max_length=50, null=True)),
                ('val16', models.CharField(blank=True, default='Val16', max_length=50, null=True)),
                ('val17', models.CharField(blank=True, default='Val17', max_length=50, null=True)),
                ('val18', models.CharField(blank=True, default='Val18', max_length=50, null=True)),
                ('val19', models.CharField(blank=True, default='Val19', max_length=50, null=True)),
                ('val20', models.CharField(blank=True, default='Val20', max_length=50, null=True)),
                ('val21', models.CharField(blank=True, default='Val21', max_length=50, null=True)),
                ('val22', models.CharField(blank=True, default='Val22', max_length=50, null=True)),
                ('val23', models.CharField(blank=True, default='Val23', max_length=50, null=True)),
                ('val24', models.CharField(blank=True, default='Val24', max_length=50, null=True)),
                ('val25', models.CharField(blank=True, default='Val25', max_length=50, null=True)),
                ('val26', models.CharField(blank=True, default='Val26', max_length=50, null=True)),
                ('val27', models.CharField(blank=True, default='Val27', max_length=50, null=True)),
                ('val28', models.CharField(blank=True, default='Val28', max_length=50, null=True)),
                ('val29', models.CharField(blank=True, default='Val29', max_length=50, null=True)),
                ('val30', models.CharField(blank=True, default='Val30', max_length=50, null=True)),
                ('val31', models.CharField(blank=True, default='Val31', max_length=50, null=True)),
                ('val32', models.CharField(blank=True, default='Val32', max_length=50, null=True)),
                ('val0_check_view', models.BooleanField(default=True)),
                ('val1_check_view', models.BooleanField(default=True)),
                ('val2_check_view', models.BooleanField(default=True)),
                ('val3_check_view', models.BooleanField(default=True)),
                ('val4_check_view', models.BooleanField(default=True)),
                ('val5_check_view', models.BooleanField(default=True)),
                ('val6_check_view', models.BooleanField(default=False)),
                ('val7_check_view', models.BooleanField(default=False)),
                ('val8_check_view', models.BooleanField(default=False)),
                ('val9_check_view', models.BooleanField(default=False)),
                ('val10_check_view', models.BooleanField(default=False)),
                ('val11_check_view', models.BooleanField(default=False)),
                ('val12_check_view', models.BooleanField(default=False)),
                ('val13_check_view', models.BooleanField(default=False)),
                ('val14_check_view', models.BooleanField(default=False)),
                ('val15_check_view', models.BooleanField(default=False)),
                ('val16_check_view', models.BooleanField(default=False)),
                ('val17_check_view', models.BooleanField(default=False)),
                ('val18_check_view', models.BooleanField(default=False)),
                ('val19_check_view', models.BooleanField(default=False)),
                ('val20_check_view', models.BooleanField(default=False)),
                ('val21_check_view', models.BooleanField(default=False)),
                ('val22_check_view', models.BooleanField(default=False)),
                ('val23_check_view', models.BooleanField(default=False)),
                ('val24_check_view', models.BooleanField(default=False)),
                ('val25_check_view', models.BooleanField(default=False)),
                ('val26_check_view', models.BooleanField(default=False)),
                ('val27_check_view', models.BooleanField(default=False)),
                ('val28_check_view', models.BooleanField(default=False)),
                ('val29_check_view', models.BooleanField(default=False)),
                ('val30_check_view', models.BooleanField(default=False)),
                ('val31_check_view', models.BooleanField(default=False)),
                ('val32_check_view', models.BooleanField(default=False)),
                ('imei_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.clientlistdevice')),
            ],
        ),
    ]
